-- Create bid_history table
CREATE TABLE bid_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    item_title TEXT NOT NULL,
    previous_bid NUMERIC(10, 2) NOT NULL,
    bid_amount NUMERIC(10, 2) NOT NULL,
    bidder_name TEXT NOT NULL,
    table_number INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Add foreign key reference to auction_items table
    CONSTRAINT fk_auction_item
        FOREIGN KEY (item_id)
        REFERENCES auction_items (id)
        ON DELETE CASCADE
);

-- Add indexes for better query performance
CREATE INDEX idx_bid_history_item_id ON bid_history(item_id);
CREATE INDEX idx_bid_history_created_at ON bid_history(created_at);

-- Add RLS policies
ALTER TABLE bid_history ENABLE ROW LEVEL SECURITY;

-- Allow anyone to view bid history
CREATE POLICY "Allow anonymous read access" 
ON bid_history FOR SELECT 
TO anon
USING (true);

-- Allow authenticated users to insert bid history
CREATE POLICY "Allow authenticated insert" 
ON bid_history FOR INSERT 
TO authenticated
WITH CHECK (true);

-- Allow anonymous users to insert bid history
CREATE POLICY "Allow anonymous insert" 
ON bid_history FOR INSERT 
TO anon
WITH CHECK (true);
